repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-yaml

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10

# -   repo: https://github.com/PyCQA/flake8
#     rev: 5.0.4
#     hooks:
#     -   id: flake8
